WIDTH = 800
HEIGHT = 600
FONT = "freesansbold.ttf"
TITLE = "Space Invaders"
BG              = "assets/bg.jpg"
PLAYER_IMAGE    = "assets/spaceship.png"
ENEMY_IMAGE     = "assets/alien.png"
BULLET_IMAGE    = "assets/bullet.png"
FPS = 60
DEF_ENEMY_SPEED = 1
DEF_BULLETS = 5
DEF_BULLET_SPEED = 10
DEF_PLAYER_SPEED = 0.25
DEF_MAX_SPEED = 0.5
MAX_X = 800
MAX_Y = -200
MIN_Y = -200
MIN_X = 100